theme = "casper-fork"
baseurl = "https://archive.seb.st/"
languageCode = "en-us"
title = "[ARCHIVED BLOG] seb.st"
Copyright = "© 2016 -2019 All rights reserved."
uglyURLs = true
disablePathToLower = true
canonifyurls = true
paginate = 5


[params]
  description = "[ARCHIVED BLOG] Thoughts, stories and ideas. By Sebastian Steins."
  author = "Sebastian Steins"
  hideHUGOSupport = false
  RSSLink = "index.xml" # workaround for bug https://github.com/spf13/hugo/issues/175
  googleAnalyticsUserID = "UA-437457-19"

  [permalinks]
      post = "/blog/:filename"
